CodingEvents/Models/Event.cs
using System.ComponentModel.DataAnnotations;

namespace CodingEvents.Models;

public class Event
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? ContactEmail { get; set; }
    public EventCategory Category { get; set; }
    public int CategoryId { get; set; }
    public ICollection<Tag>? Tags { get; set; }

    public Event(){}
    public Event(string? name, string? description, string? contactEmail)
    {
        Name = name;
        Description = description;
        ContactEmail = contactEmail;
        Tags = [];
    }


    public override string ToString()
    {
        return Name ??= "No name provided";
    }

    public override bool Equals(object? obj)
    {
        return obj is Event @event && Id == @event.Id;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(Id);
    }
}

CodingEvents/Controllers/EventsController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodingEvents.Controllers;

[Authorize]
public class EventsController : Controller
{
    private EventDbContext context;

    public EventsController(EventDbContext dbContext)
    {
        context = dbContext;
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        List<Event> events = context.Events.Include(e => e.Category).ToList();

        return View(events);
    }

    [HttpGet]
    public IActionResult Add()
    {
        List<EventCategory> categories = context.EventCategories.ToList();
        AddEventViewModel addEventViewModel = new(categories);

        return View(addEventViewModel);
    }

    [HttpPost]
    public IActionResult Add(AddEventViewModel addEventViewModel)
    {
        if (ModelState.IsValid)
        {
            EventCategory category = context.EventCategories.Find(addEventViewModel.CategoryId);

            Event newEvent =
                new()
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Category = category
                };
            context.Events.Add(newEvent);
            context.SaveChanges();

            return Redirect("/events");
        }
        return View(addEventViewModel);
    }

    public IActionResult Delete()
    {
        ViewBag.events = context.Events.ToList();

        return View();
    }

    [HttpPost]
    public IActionResult Delete(int[] eventIds)
    {
        foreach (int eventId in eventIds)
        {
            Event? theEvent = context.Events.Find(eventId);
            if (theEvent is null) break;
            
            context.Events.Remove(theEvent);
        }
        context.SaveChanges();

        return Redirect("/events");
    }

    public IActionResult Detail(int id)
    {
        Event theEvent = context.Events
            .Include(e => e.Category)
            .Include(e => e.Tags)
            .Single(e => e.Id == id);
        EventDetailViewModel viewModel = new(theEvent);
        return View(viewModel);
    }
}

CodingEvents/Controllers/TagController.cs
using CodingEvents.Data;
using CodingEvents.Models;
using CodingEvents.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodingEvents;

public class TagController : Controller
{
    private EventDbContext context;

    public TagController(EventDbContext dbContext)
    {
        context = dbContext;
    }

    // GET: /<controller>/
    public IActionResult Index()
    {
        List<Tag> tags = context.Tags.ToList();
        return View(tags);
    }

    public IActionResult Add()
    {
        Tag tag = new();
        return View(tag);
    }

    [HttpPost]
    public IActionResult Add(Tag tag)
    {
        if (ModelState.IsValid)
        {
            context.Tags.Add(tag);
            context.SaveChanges();
            return Redirect("/Tag");
        }

        return View(tag);
    }

    public IActionResult AddEvent(int id)
    {
        Event theEvent = context.Events.Find(id);
        List<Tag> possibleTags = context.Tags.ToList();

        AddEventTagViewModel viewModel = new AddEventTagViewModel(theEvent, possibleTags);

        return View(viewModel);
    }

    [HttpPost]
    public IActionResult AddEvent(AddEventTagViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            int eventId = viewModel.EventId;
            int tagId = viewModel.TagId;

            Event theEvent = context
                .Events.Include(e => e.Tags)
                .Where(e => e.Id == eventId)
                .First();
            Tag theTag = context.Tags.Where(t => t.Id == tagId).First();

            theEvent.Tags.Add(theTag);

            context.SaveChanges();

            return Redirect("/Events/Detail/" + eventId);
        }

        return View(viewModel);
    }

    public IActionResult Detail(int id)
    {
        Tag theTag = context.Tags.Include(e => e.Events).Where(t => t.Id == id).First();

        return View(theTag);
    }
}

CodingEvents/Views/Events/Add.cshtml
@using CodingEvents.ViewModels
@model AddEventViewModel

<form method="post" asp-controller="Events" asp-action="Add">
    <div class="form-group">
        <label asp-for="Name">Event Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email</label>
        <input asp-for="ContactEmail" />
        <span asp-validation-for="ContactEmail" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" asp-items="Model.Categories"></select>
        <a asp-controller="Employer" asp-action="Create">Add Employer</a>
    </div>
    <input type="submit" value="Add Event" class="btn btn-primary">
</form>

CodingEvents/Views/Events/Delete.cshtml
@{
}

<h1>Delete Event</h1>

<form method="post">
    @foreach (var codingEvent in ViewBag.events)
    {
        <div class="form-group">
            <label>
                <input 
                    type="checkbox" 
                    name="eventIds" 
                    value="@codingEvent.Id"
                >
                <span>@codingEvent.Name</span>
            </label>
        </div>
    }
    
    <input type="submit" value="Delete Selected Events" class="btn btn-danger">
</form>

CodingEvents/Views/Events/Detail.cshtml
@using CodingEvents.ViewModels
@model EventDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Description</th>
        <td>@Model.Description</td>
    </tr>
    <tr>
        <th>Contact Email</th>
        <td>@Model.ContactEmail</td>
    </tr>
    <tr>
        <th>Category</th>
        <td>@Model.CategoryName</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>@Model.TagText</td>
    </tr>
</table>
<a asp-controller="Tag" asp-action="AddEvent" asp-route-id="@Model.EventId">Add Tag</a>

CodingEvents/Views/Events/Index.cshtml
@using CodingEvents.Models
@model List<Event>

<h1>Coding Events</h1>
<p>
    <a asp-controller="events" asp-action="add">Add Event</a>
</p>
<p>
    <a asp-controller="events" asp-action="delete">Delete Event</a>
</p>
@if (Model.Count == 0)
{
    <h2>No Events Yet!</h2>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Descripton</th>
                <th>Contact Email</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var codingEvent in Model)
            {
                <tr>
                    <td>@codingEvent.Id</td>
                    <td>@codingEvent.Name</td>
                    <td>@codingEvent.Description</td>
                    <td>@codingEvent.ContactEmail</td>
                    <td>@codingEvent.Category.Name</td>
                </tr>
            }
        </tbody>
    </table>
}